name: Python Application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:32
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Analysing the code
      run: |
        make lint
    - name: Testing the code with pytest
      run: |
        make test