name: Python Application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:32
      volumes: 
        - ./:/app
    steps:
    - name: Set up Python
      run: ls -la